# Generated by Django 2.2.4 on 2019-08-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='register_time',
            new_name='date_of_register',
        ),
    ]
